/* Shared full-screen photo viewer for player career galleries. */
(()=>{
 const dialog=document.createElement('dialog');dialog.className='gallery-viewer';dialog.setAttribute('aria-label','Career gallery photo viewer');
 dialog.innerHTML='<div class="gallery-viewer-bar"><span class="gallery-viewer-count" aria-live="polite"></span><button type="button" data-action="close" autofocus aria-label="Close photo viewer">Close ✕</button></div><div class="gallery-viewer-stage"><img class="gallery-viewer-image" alt="" draggable="false"><p class="gallery-viewer-error" role="status" hidden></p></div><div class="gallery-viewer-footer"><p class="gallery-viewer-caption"></p><div class="gallery-viewer-controls"><button type="button" data-action="previous" aria-label="Previous photo">←</button><button type="button" data-action="out" aria-label="Zoom out">−</button><button type="button" data-action="reset" aria-label="Reset zoom">100%</button><button type="button" data-action="in" aria-label="Zoom in">+</button><button type="button" data-action="next" aria-label="Next photo">→</button></div><p class="gallery-viewer-hint">Pinch or tap + to zoom. Drag to move. Double-tap to zoom or reset.</p></div>';
 document.body.append(dialog);
 const stage=dialog.querySelector('.gallery-viewer-stage'),photo=dialog.querySelector('img'),caption=dialog.querySelector('.gallery-viewer-caption'),error=dialog.querySelector('.gallery-viewer-error'),button=name=>dialog.querySelector('[data-action="'+name+'"]');
 let photos=[],index=0,scale=1,x=0,y=0,baseWidth=0,baseHeight=0,opener=null,bodyOverflow='',lastTap=0,gesture=null;const pointers=new Map();
 function paint(){const maxX=Math.max(0,(baseWidth*scale-stage.clientWidth)/2),maxY=Math.max(0,(baseHeight*scale-stage.clientHeight)/2);x=Math.max(-maxX,Math.min(maxX,x));y=Math.max(-maxY,Math.min(maxY,y));photo.style.transform='translate('+x+'px,'+y+'px) scale('+scale+')';button('reset').textContent=Math.round(scale*100)+'%';button('out').disabled=scale<=1;button('in').disabled=scale>=6}
 function zoom(value){scale=Math.max(1,Math.min(6,value));if(scale===1)x=y=0;paint()}
 function fit(){if(!photo.naturalWidth||!stage.clientWidth)return;baseWidth=Math.min(stage.clientWidth-16,(stage.clientHeight-16)*photo.naturalWidth/photo.naturalHeight,photo.naturalWidth);baseHeight=baseWidth*photo.naturalHeight/photo.naturalWidth;photo.style.width=baseWidth+'px';photo.style.height=baseHeight+'px';paint()}
 function show(next){index=(next+photos.length)%photos.length;scale=1;x=y=0;pointers.clear();gesture=null;lastTap=0;photo.style.visibility='hidden';error.hidden=true;const item=photos[index];caption.textContent=item.caption;photo.alt=item.caption||'Handball career photo';dialog.querySelector('.gallery-viewer-count').textContent=(index+1)+' of '+photos.length;button('previous').hidden=button('next').hidden=photos.length<2;photo.src=item.src;paint();if(photo.complete&&photo.naturalWidth){fit();photo.style.visibility='visible'}}
 photo.onload=()=>{fit();photo.style.visibility='visible'};photo.onerror=()=>{error.textContent='This photo could not be loaded. Close the viewer and try again.';error.hidden=false};
 document.addEventListener('click',event=>{const target=event.target.closest('.gallery-photo-open');if(!target)return;const gallery=target.closest('#gallery');if(!gallery)return;const buttons=Array.from(gallery.querySelectorAll('.gallery-photo-open'));photos=buttons.map(b=>{const image=b.querySelector('img');return {src:image.currentSrc||image.src,caption:image.title||b.closest('.photo-card')?.querySelector('.photo-cap')?.textContent||image.alt||''}});opener=target;bodyOverflow=document.body.style.overflow;document.body.style.overflow='hidden';dialog.showModal();show(buttons.indexOf(target))});
 function close(){dialog.close()}
 dialog.addEventListener('close',()=>{document.body.style.overflow=bodyOverflow;pointers.clear();gesture=null;opener?.focus();photo.removeAttribute('src')});
 dialog.addEventListener('click',event=>{const action=event.target.closest('[data-action]')?.dataset.action;if(action==='close')close();if(action==='in')zoom(scale*1.5);if(action==='out')zoom(scale/1.5);if(action==='reset')zoom(1);if(action==='previous')show(index-1);if(action==='next')show(index+1)});
 dialog.addEventListener('keydown',event=>{const actions={ArrowLeft:()=>show(index-1),ArrowRight:()=>show(index+1),'+':()=>zoom(scale*1.5),'=':()=>zoom(scale*1.5),'-':()=>zoom(scale/1.5),'0':()=>zoom(1)};if(actions[event.key]){event.preventDefault();actions[event.key]()}});
 function measure(){const points=Array.from(pointers.values());if(points.length>=2){const [a,b]=points;return {cx:(a.x+b.x)/2,cy:(a.y+b.y)/2,distance:Math.hypot(a.x-b.x,a.y-b.y)}}return {cx:points[0]?.x||0,cy:points[0]?.y||0,distance:0}}
 function startGesture(){const m=measure();gesture={...m,x,y,scale,moved:false,count:pointers.size}}
 stage.addEventListener('pointerdown',event=>{if(event.pointerType==='mouse'&&event.button!==0)return;stage.setPointerCapture(event.pointerId);pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});startGesture()});
 stage.addEventListener('pointermove',event=>{if(!pointers.has(event.pointerId)||!gesture)return;pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});const m=measure(),dx=m.cx-gesture.cx,dy=m.cy-gesture.cy;if(Math.hypot(dx,dy)>5)gesture.moved=true;if(pointers.size>=2&&gesture.distance>0){scale=Math.max(1,Math.min(6,gesture.scale*m.distance/gesture.distance));gesture.moved=true}x=gesture.x+dx;y=gesture.y+dy;paint()});
 function endPointer(event){if(!pointers.has(event.pointerId))return;const tap=event.type==='pointerup'&&gesture&&!gesture.moved&&gesture.count===1;pointers.delete(event.pointerId);if(tap){const now=Date.now();if(now-lastTap<300){zoom(scale>1?1:2.5);lastTap=0}else lastTap=now}else lastTap=0;if(pointers.size)startGesture();else gesture=null}
 stage.addEventListener('pointerup',endPointer);stage.addEventListener('pointercancel',endPointer);stage.addEventListener('wheel',event=>{event.preventDefault();zoom(scale*(event.deltaY<0?1.15:1/1.15))},{passive:false});
 window.addEventListener('resize',()=>{if(dialog.open)fit()});
})();
